name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.LANGUAGE_STATS_TOKEN }}
          user: gamerplant3
          template: classic
          base: ""
          # Language Plugin Settings
          plugin_languages: yes
          plugin_languages_ignored: html, css, ruby
          
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          repositories_forks: no              # exclude forks
          plugin_languages_indepth: no        # prevent blank timeouts
          plugin_languages_limit: 8           # display up to 8 languages
          repositories_batch: 100             # scan up to 100 repos
          plugin_languages_threshold: 0%      # don't hide small percentages
          plugin_languages_skipped: ""        # Ensure nothing is being accidentally ignored
          filename: github-metrics.svg
